[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"

[[redirects]]
  from = "/*"
  to = "https://hireaubrey.com/:splat"
  status = 301
  force = true
  conditions = { Host = "hire.aubreypwd.com" }